version: "3.6"
services:
    www:
        build: .
        restart: always
        ports:
            - "2023:80"
        volumes:
            - ./www:/var/www/html
            - ./log:/var/log/apache2
        links:
            - db
        networks:
            - default
      db:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=untukkatakog
            - MYSQL_USER=user
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            - PMA_HOST=mysql
            - MYSQL_USER=user
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=test
volumes:
    persistent: